"""
56-Style Catalog — Declarative style profiles for slide content generation.

8 families × 7 styles each = 56 styles.
Each style is a StyleProfile dataclass from models.py.
Every style has unique presentation_rules and reading_rules.
"""

from app.mcp.brain_mcp.research.models import StyleProfile, SlideKind

# All 56 styles organized by family
STYLE_CATALOG: dict[str, StyleProfile] = {}


def _register(profile: StyleProfile) -> None:
    STYLE_CATALOG[profile.style_id] = profile


# ════════════════════════════════════════════════════════════════════
# FAMILY 1: Fundraise Core (8 styles)
# ════════════════════════════════════════════════════════════════════

_register(StyleProfile(
    style_id="yc_crisp",
    family="fundraise_core",
    headline_mode="metric",
    sentence_density="sparse",
    bullet_tempo="tight",
    tone="cold_data",
    evidence_density="heavy",
    preferred_slide_types=["market", "traction", "financial", "ask"],
    presentation_rules={
        "max_words_title": 6,
        "max_bullets": 4,
        "bullet_starts_with": "metric_or_verb",
        "hero_stat_required": True,
        "no_adjectives": True,
        "title_format": "metric_headline",
        "subtitle_allowed": False,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": True,
        "data_first": True,
        "max_body_sections": 3,
        "paragraph_max_sentences": 4,
    },
    fluff_tolerance=0.0,
    number_format="compact",
    citation_style="inline",
    visual_preference="chart_heavy",
    max_bullets_presentation=4,
    max_words_per_bullet=12,
))

_register(StyleProfile(
    style_id="sequoia_narrative",
    family="fundraise_core",
    headline_mode="statement",
    sentence_density="moderate",
    bullet_tempo="flowing",
    tone="authoritative_storytelling",
    evidence_density="heavy",
    preferred_slide_types=["problem", "solution", "why_now", "market"],
    presentation_rules={
        "max_words_title": 8,
        "max_bullets": 5,
        "bullet_starts_with": "narrative_hook",
        "hero_stat_required": False,
        "no_adjectives": False,
        "title_format": "statement_of_belief",
        "subtitle_allowed": True,
        "story_arc_required": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": True,
        "data_first": False,
        "narrative_framing": True,
        "max_body_sections": 4,
        "paragraph_max_sentences": 6,
    },
    fluff_tolerance=0.1,
    number_format="abbreviated",
    citation_style="footnote",
    visual_preference="image_accent",
    max_bullets_presentation=5,
    max_words_per_bullet=15,
))

_register(StyleProfile(
    style_id="benchmark_product_first",
    family="fundraise_core",
    headline_mode="provocative",
    sentence_density="sparse",
    bullet_tempo="staccato",
    tone="product_obsessed",
    evidence_density="moderate",
    preferred_slide_types=["product_demo", "solution", "traction", "competition"],
    presentation_rules={
        "max_words_title": 5,
        "max_bullets": 3,
        "bullet_starts_with": "product_feature_or_metric",
        "hero_stat_required": False,
        "no_adjectives": True,
        "title_format": "provocative_question_or_insight",
        "subtitle_allowed": False,
        "demo_screenshot_preferred": True,
    },
    reading_rules={
        "include_assumptions": False,
        "include_risks": True,
        "citation_required": False,
        "data_first": False,
        "product_walkthrough": True,
        "max_body_sections": 3,
        "paragraph_max_sentences": 3,
    },
    fluff_tolerance=0.0,
    number_format="compact",
    citation_style="inline",
    visual_preference="product_screenshot",
    max_bullets_presentation=3,
    max_words_per_bullet=10,
))

_register(StyleProfile(
    style_id="a16z_thesis",
    family="fundraise_core",
    headline_mode="statement",
    sentence_density="moderate",
    bullet_tempo="mixed",
    tone="thesis_driven",
    evidence_density="heavy",
    preferred_slide_types=["why_now", "market", "solution", "competition"],
    presentation_rules={
        "max_words_title": 10,
        "max_bullets": 5,
        "bullet_starts_with": "thesis_argument",
        "hero_stat_required": False,
        "no_adjectives": False,
        "title_format": "thesis_statement",
        "subtitle_allowed": True,
        "macro_trend_required": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": True,
        "data_first": False,
        "thesis_framing": True,
        "contrarian_angle": True,
        "max_body_sections": 5,
        "paragraph_max_sentences": 5,
    },
    fluff_tolerance=0.1,
    number_format="abbreviated",
    citation_style="footnote",
    visual_preference="diagram",
    max_bullets_presentation=5,
    max_words_per_bullet=15,
))

_register(StyleProfile(
    style_id="tiger_numbers_first",
    family="fundraise_core",
    headline_mode="metric",
    sentence_density="sparse",
    bullet_tempo="tight",
    tone="growth_velocity",
    evidence_density="heavy",
    preferred_slide_types=["traction", "financial", "market", "ask"],
    presentation_rules={
        "max_words_title": 4,
        "max_bullets": 4,
        "bullet_starts_with": "number",
        "hero_stat_required": True,
        "no_adjectives": True,
        "title_format": "kpi_headline",
        "subtitle_allowed": False,
        "every_bullet_has_metric": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": False,
        "citation_required": True,
        "data_first": True,
        "unit_economics_required": True,
        "max_body_sections": 3,
        "paragraph_max_sentences": 3,
    },
    fluff_tolerance=0.0,
    number_format="compact",
    citation_style="inline",
    visual_preference="kpi_dashboard",
    max_bullets_presentation=4,
    max_words_per_bullet=10,
))

_register(StyleProfile(
    style_id="first_round_founder",
    family="fundraise_core",
    headline_mode="question",
    sentence_density="moderate",
    bullet_tempo="flowing",
    tone="authentic_founder",
    evidence_density="moderate",
    preferred_slide_types=["problem", "solution", "team", "traction"],
    presentation_rules={
        "max_words_title": 8,
        "max_bullets": 5,
        "bullet_starts_with": "personal_insight_or_metric",
        "hero_stat_required": False,
        "no_adjectives": False,
        "title_format": "founder_question",
        "subtitle_allowed": True,
        "personal_anecdote_welcome": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": False,
        "data_first": False,
        "founder_voice": True,
        "max_body_sections": 4,
        "paragraph_max_sentences": 5,
    },
    fluff_tolerance=0.15,
    number_format="abbreviated",
    citation_style="inline",
    visual_preference="minimal_with_photo",
    max_bullets_presentation=5,
    max_words_per_bullet=14,
))

_register(StyleProfile(
    style_id="bessemer_cloud",
    family="fundraise_core",
    headline_mode="metric",
    sentence_density="moderate",
    bullet_tempo="mixed",
    tone="saas_analytical",
    evidence_density="heavy",
    preferred_slide_types=["financial", "traction", "market", "competition"],
    presentation_rules={
        "max_words_title": 7,
        "max_bullets": 5,
        "bullet_starts_with": "saas_metric_or_benchmark",
        "hero_stat_required": True,
        "no_adjectives": True,
        "title_format": "benchmark_comparison",
        "subtitle_allowed": True,
        "benchmark_reference_required": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": True,
        "data_first": True,
        "saas_metrics_framework": True,
        "bessemer_benchmarks": True,
        "max_body_sections": 4,
        "paragraph_max_sentences": 5,
    },
    fluff_tolerance=0.0,
    number_format="compact",
    citation_style="footnote",
    visual_preference="chart_heavy",
    max_bullets_presentation=5,
    max_words_per_bullet=12,
))

_register(StyleProfile(
    style_id="accel_growth",
    family="fundraise_core",
    headline_mode="metric",
    sentence_density="sparse",
    bullet_tempo="staccato",
    tone="growth_trajectory",
    evidence_density="heavy",
    preferred_slide_types=["traction", "financial", "gtm", "ask"],
    presentation_rules={
        "max_words_title": 5,
        "max_bullets": 4,
        "bullet_starts_with": "growth_metric",
        "hero_stat_required": True,
        "no_adjectives": True,
        "title_format": "growth_headline",
        "subtitle_allowed": False,
        "trajectory_emphasis": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": True,
        "data_first": True,
        "cohort_analysis_preferred": True,
        "max_body_sections": 3,
        "paragraph_max_sentences": 4,
    },
    fluff_tolerance=0.0,
    number_format="compact",
    citation_style="inline",
    visual_preference="line_chart_up_right",
    max_bullets_presentation=4,
    max_words_per_bullet=11,
))


# ════════════════════════════════════════════════════════════════════
# FAMILY 2: Founder Story (8 styles)
# ════════════════════════════════════════════════════════════════════

_register(StyleProfile(
    style_id="visionary_manifesto",
    family="founder_story",
    headline_mode="provocative",
    sentence_density="moderate",
    bullet_tempo="flowing",
    tone="visionary_bold",
    evidence_density="moderate",
    preferred_slide_types=["title", "problem", "solution", "why_now"],
    presentation_rules={
        "max_words_title": 8,
        "max_bullets": 4,
        "bullet_starts_with": "vision_statement",
        "hero_stat_required": False,
        "no_adjectives": False,
        "title_format": "manifesto_declaration",
        "subtitle_allowed": True,
        "future_tense_ok": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": False,
        "citation_required": False,
        "data_first": False,
        "vision_first": True,
        "max_body_sections": 4,
        "paragraph_max_sentences": 6,
    },
    fluff_tolerance=0.2,
    number_format="abbreviated",
    citation_style="appendix",
    visual_preference="hero_image",
    max_bullets_presentation=4,
    max_words_per_bullet=16,
))

_register(StyleProfile(
    style_id="scrappy_builder",
    family="founder_story",
    headline_mode="statement",
    sentence_density="sparse",
    bullet_tempo="staccato",
    tone="hustle_authentic",
    evidence_density="moderate",
    preferred_slide_types=["problem", "solution", "traction", "team"],
    presentation_rules={
        "max_words_title": 6,
        "max_bullets": 4,
        "bullet_starts_with": "action_or_result",
        "hero_stat_required": False,
        "no_adjectives": True,
        "title_format": "builder_insight",
        "subtitle_allowed": False,
        "show_resourcefulness": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": False,
        "data_first": False,
        "hustle_metrics": True,
        "max_body_sections": 3,
        "paragraph_max_sentences": 4,
    },
    fluff_tolerance=0.0,
    number_format="compact",
    citation_style="inline",
    visual_preference="minimal",
    max_bullets_presentation=4,
    max_words_per_bullet=12,
))

_register(StyleProfile(
    style_id="contrarian_insight",
    family="founder_story",
    headline_mode="provocative",
    sentence_density="moderate",
    bullet_tempo="mixed",
    tone="contrarian_intellectual",
    evidence_density="heavy",
    preferred_slide_types=["problem", "why_now", "market", "competition"],
    presentation_rules={
        "max_words_title": 10,
        "max_bullets": 4,
        "bullet_starts_with": "contrarian_claim_with_evidence",
        "hero_stat_required": False,
        "no_adjectives": False,
        "title_format": "contrarian_question",
        "subtitle_allowed": True,
        "conventional_wisdom_then_flip": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": True,
        "data_first": False,
        "alternative_hypothesis": True,
        "max_body_sections": 4,
        "paragraph_max_sentences": 5,
    },
    fluff_tolerance=0.05,
    number_format="abbreviated",
    citation_style="footnote",
    visual_preference="comparison_diagram",
    max_bullets_presentation=4,
    max_words_per_bullet=15,
))

_register(StyleProfile(
    style_id="mission_driven",
    family="founder_story",
    headline_mode="statement",
    sentence_density="moderate",
    bullet_tempo="flowing",
    tone="purposeful_urgent",
    evidence_density="moderate",
    preferred_slide_types=["problem", "solution", "why_now", "team"],
    presentation_rules={
        "max_words_title": 8,
        "max_bullets": 5,
        "bullet_starts_with": "impact_statement_or_metric",
        "hero_stat_required": False,
        "no_adjectives": False,
        "title_format": "mission_statement",
        "subtitle_allowed": True,
        "human_impact_emphasis": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": True,
        "data_first": False,
        "impact_framing": True,
        "beneficiary_stories": True,
        "max_body_sections": 4,
        "paragraph_max_sentences": 5,
    },
    fluff_tolerance=0.15,
    number_format="abbreviated",
    citation_style="inline",
    visual_preference="impact_visual",
    max_bullets_presentation=5,
    max_words_per_bullet=14,
))

_register(StyleProfile(
    style_id="deeptech_founder",
    family="founder_story",
    headline_mode="statement",
    sentence_density="dense",
    bullet_tempo="mixed",
    tone="technical_authority",
    evidence_density="heavy",
    preferred_slide_types=["solution", "product_demo", "competition", "team"],
    presentation_rules={
        "max_words_title": 8,
        "max_bullets": 5,
        "bullet_starts_with": "technical_fact",
        "hero_stat_required": False,
        "no_adjectives": True,
        "title_format": "technical_breakthrough",
        "subtitle_allowed": True,
        "jargon_acceptable_if_defined": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": True,
        "data_first": True,
        "technical_depth": True,
        "peer_review_references": True,
        "max_body_sections": 5,
        "paragraph_max_sentences": 6,
    },
    fluff_tolerance=0.0,
    number_format="scientific",
    citation_style="footnote",
    visual_preference="architecture_diagram",
    max_bullets_presentation=5,
    max_words_per_bullet=14,
))

_register(StyleProfile(
    style_id="community_led",
    family="founder_story",
    headline_mode="question",
    sentence_density="moderate",
    bullet_tempo="flowing",
    tone="community_voice",
    evidence_density="moderate",
    preferred_slide_types=["traction", "problem", "solution", "gtm"],
    presentation_rules={
        "max_words_title": 8,
        "max_bullets": 5,
        "bullet_starts_with": "community_metric_or_quote",
        "hero_stat_required": False,
        "no_adjectives": False,
        "title_format": "community_insight",
        "subtitle_allowed": True,
        "user_testimonials_welcome": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": False,
        "data_first": False,
        "community_evidence": True,
        "user_quotes_included": True,
        "max_body_sections": 4,
        "paragraph_max_sentences": 5,
    },
    fluff_tolerance=0.1,
    number_format="abbreviated",
    citation_style="inline",
    visual_preference="community_collage",
    max_bullets_presentation=5,
    max_words_per_bullet=14,
))

_register(StyleProfile(
    style_id="craft_obsessed",
    family="founder_story",
    headline_mode="statement",
    sentence_density="moderate",
    bullet_tempo="staccato",
    tone="perfectionist_precise",
    evidence_density="moderate",
    preferred_slide_types=["product_demo", "solution", "competition", "team"],
    presentation_rules={
        "max_words_title": 6,
        "max_bullets": 3,
        "bullet_starts_with": "craft_detail",
        "hero_stat_required": False,
        "no_adjectives": False,
        "title_format": "craft_statement",
        "subtitle_allowed": False,
        "attention_to_detail_emphasis": True,
    },
    reading_rules={
        "include_assumptions": False,
        "include_risks": True,
        "citation_required": False,
        "data_first": False,
        "process_description": True,
        "design_rationale": True,
        "max_body_sections": 3,
        "paragraph_max_sentences": 4,
    },
    fluff_tolerance=0.0,
    number_format="full",
    citation_style="appendix",
    visual_preference="product_detail",
    max_bullets_presentation=3,
    max_words_per_bullet=12,
))

_register(StyleProfile(
    style_id="operator_confessional",
    family="founder_story",
    headline_mode="question",
    sentence_density="moderate",
    bullet_tempo="flowing",
    tone="candid_operational",
    evidence_density="moderate",
    preferred_slide_types=["problem", "traction", "team", "financial"],
    presentation_rules={
        "max_words_title": 8,
        "max_bullets": 5,
        "bullet_starts_with": "lesson_or_metric",
        "hero_stat_required": False,
        "no_adjectives": False,
        "title_format": "honest_admission",
        "subtitle_allowed": True,
        "failures_acknowledged": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": False,
        "data_first": False,
        "operational_learnings": True,
        "pivot_history": True,
        "max_body_sections": 4,
        "paragraph_max_sentences": 5,
    },
    fluff_tolerance=0.05,
    number_format="abbreviated",
    citation_style="inline",
    visual_preference="timeline",
    max_bullets_presentation=5,
    max_words_per_bullet=14,
))


# ════════════════════════════════════════════════════════════════════
# FAMILY 3: Investor Diligence (8 styles)
# ════════════════════════════════════════════════════════════════════

_register(StyleProfile(
    style_id="board_memo",
    family="investor_diligence",
    headline_mode="statement",
    sentence_density="dense",
    bullet_tempo="mixed",
    tone="executive_formal",
    evidence_density="heavy",
    preferred_slide_types=["financial", "market", "traction", "competition"],
    presentation_rules={
        "max_words_title": 10,
        "max_bullets": 6,
        "bullet_starts_with": "conclusion_or_recommendation",
        "hero_stat_required": False,
        "no_adjectives": True,
        "title_format": "memo_subject_line",
        "subtitle_allowed": True,
        "executive_summary_first": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": True,
        "data_first": True,
        "recommendation_framing": True,
        "action_items_required": True,
        "max_body_sections": 6,
        "paragraph_max_sentences": 6,
    },
    fluff_tolerance=0.0,
    number_format="full",
    citation_style="footnote",
    visual_preference="table",
    max_bullets_presentation=6,
    max_words_per_bullet=15,
))

_register(StyleProfile(
    style_id="analyst_brief",
    family="investor_diligence",
    headline_mode="metric",
    sentence_density="moderate",
    bullet_tempo="tight",
    tone="analytical_neutral",
    evidence_density="heavy",
    preferred_slide_types=["market", "competition", "financial", "traction"],
    presentation_rules={
        "max_words_title": 8,
        "max_bullets": 5,
        "bullet_starts_with": "data_point_or_finding",
        "hero_stat_required": True,
        "no_adjectives": True,
        "title_format": "analyst_finding",
        "subtitle_allowed": True,
        "source_attribution_mandatory": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": True,
        "data_first": True,
        "methodology_noted": True,
        "confidence_intervals": True,
        "max_body_sections": 5,
        "paragraph_max_sentences": 5,
    },
    fluff_tolerance=0.0,
    number_format="full",
    citation_style="footnote",
    visual_preference="chart_heavy",
    max_bullets_presentation=5,
    max_words_per_bullet=13,
))

_register(StyleProfile(
    style_id="ic_memo",
    family="investor_diligence",
    headline_mode="statement",
    sentence_density="dense",
    bullet_tempo="mixed",
    tone="investment_committee",
    evidence_density="heavy",
    preferred_slide_types=["market", "financial", "competition", "ask"],
    presentation_rules={
        "max_words_title": 10,
        "max_bullets": 5,
        "bullet_starts_with": "investment_thesis_point",
        "hero_stat_required": False,
        "no_adjectives": True,
        "title_format": "ic_decision_header",
        "subtitle_allowed": True,
        "pros_cons_format": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": True,
        "data_first": True,
        "bear_case_required": True,
        "bull_case_required": True,
        "max_body_sections": 6,
        "paragraph_max_sentences": 6,
    },
    fluff_tolerance=0.0,
    number_format="full",
    citation_style="footnote",
    visual_preference="comparison_table",
    max_bullets_presentation=5,
    max_words_per_bullet=15,
))

_register(StyleProfile(
    style_id="diligence_pack",
    family="investor_diligence",
    headline_mode="statement",
    sentence_density="dense",
    bullet_tempo="tight",
    tone="due_diligence_formal",
    evidence_density="heavy",
    preferred_slide_types=["financial", "market", "competition", "team"],
    presentation_rules={
        "max_words_title": 8,
        "max_bullets": 6,
        "bullet_starts_with": "verified_fact",
        "hero_stat_required": False,
        "no_adjectives": True,
        "title_format": "diligence_category",
        "subtitle_allowed": True,
        "cross_reference_required": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": True,
        "data_first": True,
        "verification_status": True,
        "red_flags_section": True,
        "max_body_sections": 6,
        "paragraph_max_sentences": 5,
    },
    fluff_tolerance=0.0,
    number_format="full",
    citation_style="footnote",
    visual_preference="checklist_table",
    max_bullets_presentation=6,
    max_words_per_bullet=14,
))

_register(StyleProfile(
    style_id="unit_economics_hardline",
    family="investor_diligence",
    headline_mode="metric",
    sentence_density="sparse",
    bullet_tempo="tight",
    tone="financial_rigor",
    evidence_density="heavy",
    preferred_slide_types=["financial", "traction", "gtm", "ask"],
    presentation_rules={
        "max_words_title": 5,
        "max_bullets": 4,
        "bullet_starts_with": "unit_metric",
        "hero_stat_required": True,
        "no_adjectives": True,
        "title_format": "metric_ratio",
        "subtitle_allowed": False,
        "ltv_cac_required": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": True,
        "data_first": True,
        "sensitivity_analysis": True,
        "cohort_breakdown": True,
        "max_body_sections": 4,
        "paragraph_max_sentences": 4,
    },
    fluff_tolerance=0.0,
    number_format="compact",
    citation_style="inline",
    visual_preference="waterfall_chart",
    max_bullets_presentation=4,
    max_words_per_bullet=10,
))

_register(StyleProfile(
    style_id="market_map_brief",
    family="investor_diligence",
    headline_mode="comparison",
    sentence_density="moderate",
    bullet_tempo="mixed",
    tone="landscape_analytical",
    evidence_density="heavy",
    preferred_slide_types=["market", "competition", "why_now", "gtm"],
    presentation_rules={
        "max_words_title": 8,
        "max_bullets": 5,
        "bullet_starts_with": "market_segment_or_player",
        "hero_stat_required": False,
        "no_adjectives": True,
        "title_format": "landscape_header",
        "subtitle_allowed": True,
        "market_map_visual_required": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": True,
        "data_first": True,
        "competitive_positioning": True,
        "segment_analysis": True,
        "max_body_sections": 5,
        "paragraph_max_sentences": 5,
    },
    fluff_tolerance=0.0,
    number_format="abbreviated",
    citation_style="footnote",
    visual_preference="market_map",
    max_bullets_presentation=5,
    max_words_per_bullet=14,
))

_register(StyleProfile(
    style_id="risk_adjusted_case",
    family="investor_diligence",
    headline_mode="statement",
    sentence_density="dense",
    bullet_tempo="mixed",
    tone="risk_aware_measured",
    evidence_density="heavy",
    preferred_slide_types=["financial", "market", "competition", "ask"],
    presentation_rules={
        "max_words_title": 9,
        "max_bullets": 5,
        "bullet_starts_with": "risk_or_mitigant",
        "hero_stat_required": False,
        "no_adjectives": True,
        "title_format": "risk_scenario_header",
        "subtitle_allowed": True,
        "base_bear_bull_required": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": True,
        "data_first": True,
        "scenario_analysis": True,
        "probability_weighted": True,
        "max_body_sections": 5,
        "paragraph_max_sentences": 6,
    },
    fluff_tolerance=0.0,
    number_format="full",
    citation_style="footnote",
    visual_preference="scenario_table",
    max_bullets_presentation=5,
    max_words_per_bullet=15,
))

_register(StyleProfile(
    style_id="portfolio_fit",
    family="investor_diligence",
    headline_mode="comparison",
    sentence_density="moderate",
    bullet_tempo="mixed",
    tone="portfolio_strategic",
    evidence_density="moderate",
    preferred_slide_types=["market", "competition", "financial", "team"],
    presentation_rules={
        "max_words_title": 8,
        "max_bullets": 5,
        "bullet_starts_with": "portfolio_comparison_or_synergy",
        "hero_stat_required": False,
        "no_adjectives": True,
        "title_format": "portfolio_positioning",
        "subtitle_allowed": True,
        "comparable_analysis": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": True,
        "data_first": False,
        "portfolio_context": True,
        "comparable_companies": True,
        "max_body_sections": 4,
        "paragraph_max_sentences": 5,
    },
    fluff_tolerance=0.05,
    number_format="abbreviated",
    citation_style="footnote",
    visual_preference="comparison_matrix",
    max_bullets_presentation=5,
    max_words_per_bullet=14,
))


# ════════════════════════════════════════════════════════════════════
# FAMILY 4: Product / GTM (8 styles)
# ════════════════════════════════════════════════════════════════════

_register(StyleProfile(
    style_id="b2b_enterprise",
    family="product_gtm",
    headline_mode="statement",
    sentence_density="moderate",
    bullet_tempo="mixed",
    tone="enterprise_professional",
    evidence_density="moderate",
    preferred_slide_types=["solution", "competition", "gtm", "financial"],
    presentation_rules={
        "max_words_title": 8,
        "max_bullets": 5,
        "bullet_starts_with": "enterprise_value_prop",
        "hero_stat_required": False,
        "no_adjectives": False,
        "title_format": "value_proposition",
        "subtitle_allowed": True,
        "roi_framing": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": True,
        "data_first": False,
        "buyer_journey_mapping": True,
        "integration_requirements": True,
        "max_body_sections": 4,
        "paragraph_max_sentences": 5,
    },
    fluff_tolerance=0.1,
    number_format="abbreviated",
    citation_style="footnote",
    visual_preference="process_flow",
    max_bullets_presentation=5,
    max_words_per_bullet=14,
))

_register(StyleProfile(
    style_id="plg_motion",
    family="product_gtm",
    headline_mode="metric",
    sentence_density="sparse",
    bullet_tempo="staccato",
    tone="product_growth",
    evidence_density="heavy",
    preferred_slide_types=["traction", "product_demo", "gtm", "financial"],
    presentation_rules={
        "max_words_title": 6,
        "max_bullets": 4,
        "bullet_starts_with": "product_metric_or_funnel_step",
        "hero_stat_required": True,
        "no_adjectives": True,
        "title_format": "growth_loop_headline",
        "subtitle_allowed": False,
        "funnel_metrics_required": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": False,
        "data_first": True,
        "growth_loop_analysis": True,
        "activation_metrics": True,
        "max_body_sections": 3,
        "paragraph_max_sentences": 4,
    },
    fluff_tolerance=0.0,
    number_format="compact",
    citation_style="inline",
    visual_preference="funnel_chart",
    max_bullets_presentation=4,
    max_words_per_bullet=11,
))

_register(StyleProfile(
    style_id="consumer_viral",
    family="product_gtm",
    headline_mode="provocative",
    sentence_density="sparse",
    bullet_tempo="staccato",
    tone="consumer_energetic",
    evidence_density="moderate",
    preferred_slide_types=["problem", "solution", "traction", "gtm"],
    presentation_rules={
        "max_words_title": 6,
        "max_bullets": 4,
        "bullet_starts_with": "user_behavior_or_viral_metric",
        "hero_stat_required": True,
        "no_adjectives": False,
        "title_format": "consumer_hook",
        "subtitle_allowed": False,
        "virality_coefficient_shown": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": False,
        "data_first": True,
        "viral_loop_explained": True,
        "retention_cohorts": True,
        "max_body_sections": 3,
        "paragraph_max_sentences": 4,
    },
    fluff_tolerance=0.1,
    number_format="compact",
    citation_style="inline",
    visual_preference="social_proof_grid",
    max_bullets_presentation=4,
    max_words_per_bullet=12,
))

_register(StyleProfile(
    style_id="marketplace_liquidity",
    family="product_gtm",
    headline_mode="metric",
    sentence_density="moderate",
    bullet_tempo="mixed",
    tone="marketplace_analytical",
    evidence_density="heavy",
    preferred_slide_types=["market", "traction", "gtm", "financial"],
    presentation_rules={
        "max_words_title": 7,
        "max_bullets": 5,
        "bullet_starts_with": "supply_demand_metric",
        "hero_stat_required": True,
        "no_adjectives": True,
        "title_format": "marketplace_kpi",
        "subtitle_allowed": True,
        "liquidity_metrics_shown": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": True,
        "data_first": True,
        "supply_demand_dynamics": True,
        "take_rate_analysis": True,
        "max_body_sections": 4,
        "paragraph_max_sentences": 5,
    },
    fluff_tolerance=0.0,
    number_format="compact",
    citation_style="inline",
    visual_preference="supply_demand_chart",
    max_bullets_presentation=5,
    max_words_per_bullet=13,
))

_register(StyleProfile(
    style_id="fintech_trust",
    family="product_gtm",
    headline_mode="statement",
    sentence_density="moderate",
    bullet_tempo="tight",
    tone="regulatory_trustworthy",
    evidence_density="heavy",
    preferred_slide_types=["solution", "market", "competition", "financial"],
    presentation_rules={
        "max_words_title": 8,
        "max_bullets": 5,
        "bullet_starts_with": "compliance_or_trust_metric",
        "hero_stat_required": False,
        "no_adjectives": True,
        "title_format": "trust_statement",
        "subtitle_allowed": True,
        "regulatory_compliance_shown": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": True,
        "data_first": True,
        "regulatory_landscape": True,
        "compliance_framework": True,
        "max_body_sections": 5,
        "paragraph_max_sentences": 5,
    },
    fluff_tolerance=0.0,
    number_format="full",
    citation_style="footnote",
    visual_preference="compliance_checklist",
    max_bullets_presentation=5,
    max_words_per_bullet=14,
))

_register(StyleProfile(
    style_id="healthtech_clinical",
    family="product_gtm",
    headline_mode="statement",
    sentence_density="dense",
    bullet_tempo="mixed",
    tone="clinical_evidence_based",
    evidence_density="heavy",
    preferred_slide_types=["solution", "market", "traction", "team"],
    presentation_rules={
        "max_words_title": 10,
        "max_bullets": 5,
        "bullet_starts_with": "clinical_outcome_or_evidence",
        "hero_stat_required": False,
        "no_adjectives": True,
        "title_format": "clinical_finding",
        "subtitle_allowed": True,
        "efficacy_data_required": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": True,
        "data_first": True,
        "clinical_trial_refs": True,
        "fda_pathway_noted": True,
        "max_body_sections": 5,
        "paragraph_max_sentences": 6,
    },
    fluff_tolerance=0.0,
    number_format="scientific",
    citation_style="footnote",
    visual_preference="clinical_data_chart",
    max_bullets_presentation=5,
    max_words_per_bullet=15,
))

_register(StyleProfile(
    style_id="climate_impact",
    family="product_gtm",
    headline_mode="statement",
    sentence_density="moderate",
    bullet_tempo="flowing",
    tone="impact_urgent",
    evidence_density="heavy",
    preferred_slide_types=["problem", "solution", "market", "why_now"],
    presentation_rules={
        "max_words_title": 8,
        "max_bullets": 5,
        "bullet_starts_with": "impact_metric_or_comparison",
        "hero_stat_required": True,
        "no_adjectives": False,
        "title_format": "impact_headline",
        "subtitle_allowed": True,
        "carbon_equivalent_shown": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": True,
        "data_first": True,
        "environmental_impact_quantified": True,
        "policy_landscape": True,
        "max_body_sections": 4,
        "paragraph_max_sentences": 5,
    },
    fluff_tolerance=0.05,
    number_format="abbreviated",
    citation_style="footnote",
    visual_preference="impact_infographic",
    max_bullets_presentation=5,
    max_words_per_bullet=14,
))

_register(StyleProfile(
    style_id="developer_tooling",
    family="product_gtm",
    headline_mode="metric",
    sentence_density="sparse",
    bullet_tempo="staccato",
    tone="developer_pragmatic",
    evidence_density="moderate",
    preferred_slide_types=["product_demo", "solution", "traction", "gtm"],
    presentation_rules={
        "max_words_title": 6,
        "max_bullets": 4,
        "bullet_starts_with": "devex_metric_or_code_example",
        "hero_stat_required": True,
        "no_adjectives": True,
        "title_format": "developer_benefit",
        "subtitle_allowed": False,
        "code_snippet_ok": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": False,
        "data_first": True,
        "api_design_details": True,
        "integration_effort": True,
        "max_body_sections": 3,
        "paragraph_max_sentences": 4,
    },
    fluff_tolerance=0.0,
    number_format="compact",
    citation_style="inline",
    visual_preference="code_snippet",
    max_bullets_presentation=4,
    max_words_per_bullet=11,
))


# ════════════════════════════════════════════════════════════════════
# FAMILY 5: Reading-Heavy (8 styles)
# ════════════════════════════════════════════════════════════════════

_register(StyleProfile(
    style_id="research_memo",
    family="reading_heavy",
    headline_mode="statement",
    sentence_density="dense",
    bullet_tempo="flowing",
    tone="research_analytical",
    evidence_density="heavy",
    preferred_slide_types=["market", "competition", "financial", "appendix"],
    presentation_rules={
        "max_words_title": 10,
        "max_bullets": 6,
        "bullet_starts_with": "finding_or_data_point",
        "hero_stat_required": False,
        "no_adjectives": True,
        "title_format": "research_finding",
        "subtitle_allowed": True,
        "methodology_footnote": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": True,
        "data_first": True,
        "methodology_section": True,
        "limitations_disclosed": True,
        "max_body_sections": 6,
        "paragraph_max_sentences": 7,
    },
    fluff_tolerance=0.0,
    number_format="full",
    citation_style="footnote",
    visual_preference="data_table",
    max_bullets_presentation=6,
    max_words_per_bullet=16,
))

_register(StyleProfile(
    style_id="whitepaper_compact",
    family="reading_heavy",
    headline_mode="statement",
    sentence_density="dense",
    bullet_tempo="flowing",
    tone="academic_accessible",
    evidence_density="heavy",
    preferred_slide_types=["problem", "solution", "market", "appendix"],
    presentation_rules={
        "max_words_title": 12,
        "max_bullets": 5,
        "bullet_starts_with": "key_finding",
        "hero_stat_required": False,
        "no_adjectives": True,
        "title_format": "academic_title",
        "subtitle_allowed": True,
        "abstract_slide_first": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": True,
        "data_first": True,
        "literature_review": True,
        "structured_abstract": True,
        "max_body_sections": 6,
        "paragraph_max_sentences": 8,
    },
    fluff_tolerance=0.0,
    number_format="scientific",
    citation_style="footnote",
    visual_preference="figure_with_caption",
    max_bullets_presentation=5,
    max_words_per_bullet=18,
))

_register(StyleProfile(
    style_id="deep_dive_appendix",
    family="reading_heavy",
    headline_mode="statement",
    sentence_density="dense",
    bullet_tempo="tight",
    tone="reference_exhaustive",
    evidence_density="heavy",
    preferred_slide_types=["appendix", "financial", "market", "competition"],
    presentation_rules={
        "max_words_title": 8,
        "max_bullets": 8,
        "bullet_starts_with": "detail_or_specification",
        "hero_stat_required": False,
        "no_adjectives": True,
        "title_format": "appendix_header",
        "subtitle_allowed": True,
        "cross_reference_to_main": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": True,
        "data_first": True,
        "exhaustive_detail": True,
        "glossary_terms": True,
        "max_body_sections": 8,
        "paragraph_max_sentences": 6,
    },
    fluff_tolerance=0.0,
    number_format="full",
    citation_style="footnote",
    visual_preference="detailed_table",
    max_bullets_presentation=8,
    max_words_per_bullet=14,
))

_register(StyleProfile(
    style_id="technical_qna",
    family="reading_heavy",
    headline_mode="question",
    sentence_density="moderate",
    bullet_tempo="mixed",
    tone="technical_expert",
    evidence_density="heavy",
    preferred_slide_types=["solution", "product_demo", "competition", "appendix"],
    presentation_rules={
        "max_words_title": 10,
        "max_bullets": 5,
        "bullet_starts_with": "answer_to_question",
        "hero_stat_required": False,
        "no_adjectives": True,
        "title_format": "technical_question",
        "subtitle_allowed": True,
        "faq_format": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": True,
        "data_first": True,
        "question_answer_format": True,
        "technical_specifications": True,
        "max_body_sections": 5,
        "paragraph_max_sentences": 5,
    },
    fluff_tolerance=0.0,
    number_format="scientific",
    citation_style="inline",
    visual_preference="architecture_diagram",
    max_bullets_presentation=5,
    max_words_per_bullet=15,
))

_register(StyleProfile(
    style_id="evidence_journal",
    family="reading_heavy",
    headline_mode="statement",
    sentence_density="dense",
    bullet_tempo="flowing",
    tone="evidence_chronicle",
    evidence_density="heavy",
    preferred_slide_types=["market", "traction", "financial", "appendix"],
    presentation_rules={
        "max_words_title": 10,
        "max_bullets": 6,
        "bullet_starts_with": "dated_evidence_point",
        "hero_stat_required": False,
        "no_adjectives": True,
        "title_format": "evidence_summary",
        "subtitle_allowed": True,
        "timeline_emphasis": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": True,
        "data_first": True,
        "chronological_ordering": True,
        "source_provenance": True,
        "max_body_sections": 6,
        "paragraph_max_sentences": 6,
    },
    fluff_tolerance=0.0,
    number_format="full",
    citation_style="footnote",
    visual_preference="annotated_timeline",
    max_bullets_presentation=6,
    max_words_per_bullet=15,
))

_register(StyleProfile(
    style_id="founder_update_letter",
    family="reading_heavy",
    headline_mode="statement",
    sentence_density="moderate",
    bullet_tempo="flowing",
    tone="candid_transparent",
    evidence_density="moderate",
    preferred_slide_types=["traction", "financial", "team", "problem"],
    presentation_rules={
        "max_words_title": 8,
        "max_bullets": 5,
        "bullet_starts_with": "update_highlight",
        "hero_stat_required": True,
        "no_adjectives": False,
        "title_format": "monthly_update_header",
        "subtitle_allowed": True,
        "wins_and_challenges_format": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": False,
        "data_first": True,
        "narrative_with_metrics": True,
        "asks_for_help_section": True,
        "max_body_sections": 5,
        "paragraph_max_sentences": 5,
    },
    fluff_tolerance=0.1,
    number_format="abbreviated",
    citation_style="inline",
    visual_preference="sparkline_kpi",
    max_bullets_presentation=5,
    max_words_per_bullet=14,
))

_register(StyleProfile(
    style_id="expert_briefing",
    family="reading_heavy",
    headline_mode="statement",
    sentence_density="dense",
    bullet_tempo="tight",
    tone="domain_expert",
    evidence_density="heavy",
    preferred_slide_types=["market", "solution", "competition", "why_now"],
    presentation_rules={
        "max_words_title": 10,
        "max_bullets": 5,
        "bullet_starts_with": "expert_assessment",
        "hero_stat_required": False,
        "no_adjectives": True,
        "title_format": "briefing_subject",
        "subtitle_allowed": True,
        "tldr_first": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": True,
        "data_first": True,
        "expert_opinion_attributed": True,
        "counterarguments_addressed": True,
        "max_body_sections": 5,
        "paragraph_max_sentences": 6,
    },
    fluff_tolerance=0.0,
    number_format="abbreviated",
    citation_style="footnote",
    visual_preference="annotated_chart",
    max_bullets_presentation=5,
    max_words_per_bullet=15,
))

_register(StyleProfile(
    style_id="casefile",
    family="reading_heavy",
    headline_mode="narrative",
    sentence_density="dense",
    bullet_tempo="flowing",
    tone="investigative_thorough",
    evidence_density="heavy",
    preferred_slide_types=["problem", "market", "competition", "appendix"],
    presentation_rules={
        "max_words_title": 10,
        "max_bullets": 6,
        "bullet_starts_with": "case_evidence",
        "hero_stat_required": False,
        "no_adjectives": True,
        "title_format": "case_header",
        "subtitle_allowed": True,
        "evidence_chain_format": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": True,
        "data_first": False,
        "narrative_evidence_chain": True,
        "primary_sources_prioritized": True,
        "max_body_sections": 6,
        "paragraph_max_sentences": 7,
    },
    fluff_tolerance=0.0,
    number_format="full",
    citation_style="footnote",
    visual_preference="evidence_board",
    max_bullets_presentation=6,
    max_words_per_bullet=16,
))


# ════════════════════════════════════════════════════════════════════
# FAMILY 6: Presentation-Heavy (8 styles)
# ════════════════════════════════════════════════════════════════════

_register(StyleProfile(
    style_id="keynote_minimal",
    family="presentation_heavy",
    headline_mode="provocative",
    sentence_density="sparse",
    bullet_tempo="staccato",
    tone="keynote_dramatic",
    evidence_density="light",
    preferred_slide_types=["title", "problem", "solution", "why_now"],
    presentation_rules={
        "max_words_title": 5,
        "max_bullets": 3,
        "bullet_starts_with": "single_powerful_phrase",
        "hero_stat_required": False,
        "no_adjectives": False,
        "title_format": "one_word_or_phrase",
        "subtitle_allowed": False,
        "full_bleed_image_preferred": True,
    },
    reading_rules={
        "include_assumptions": False,
        "include_risks": False,
        "citation_required": False,
        "data_first": False,
        "speaker_notes_carry_depth": True,
        "max_body_sections": 2,
        "paragraph_max_sentences": 3,
    },
    fluff_tolerance=0.15,
    number_format="compact",
    citation_style="appendix",
    visual_preference="full_bleed_image",
    max_bullets_presentation=3,
    max_words_per_bullet=8,
))

_register(StyleProfile(
    style_id="cinematic_reveal",
    family="presentation_heavy",
    headline_mode="narrative",
    sentence_density="sparse",
    bullet_tempo="flowing",
    tone="cinematic_suspense",
    evidence_density="light",
    preferred_slide_types=["title", "problem", "solution", "product_demo"],
    presentation_rules={
        "max_words_title": 6,
        "max_bullets": 2,
        "bullet_starts_with": "reveal_phrase",
        "hero_stat_required": False,
        "no_adjectives": False,
        "title_format": "reveal_headline",
        "subtitle_allowed": True,
        "progressive_disclosure": True,
    },
    reading_rules={
        "include_assumptions": False,
        "include_risks": False,
        "citation_required": False,
        "data_first": False,
        "suspense_structure": True,
        "max_body_sections": 2,
        "paragraph_max_sentences": 4,
    },
    fluff_tolerance=0.2,
    number_format="compact",
    citation_style="appendix",
    visual_preference="cinematic_image",
    max_bullets_presentation=2,
    max_words_per_bullet=10,
))

_register(StyleProfile(
    style_id="editorial_magazine",
    family="presentation_heavy",
    headline_mode="provocative",
    sentence_density="moderate",
    bullet_tempo="flowing",
    tone="editorial_polished",
    evidence_density="moderate",
    preferred_slide_types=["problem", "solution", "market", "why_now"],
    presentation_rules={
        "max_words_title": 8,
        "max_bullets": 4,
        "bullet_starts_with": "editorial_observation",
        "hero_stat_required": False,
        "no_adjectives": False,
        "title_format": "magazine_headline",
        "subtitle_allowed": True,
        "pull_quote_style": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": False,
        "citation_required": True,
        "data_first": False,
        "editorial_framing": True,
        "max_body_sections": 3,
        "paragraph_max_sentences": 5,
    },
    fluff_tolerance=0.15,
    number_format="abbreviated",
    citation_style="inline",
    visual_preference="editorial_layout",
    max_bullets_presentation=4,
    max_words_per_bullet=14,
))

_register(StyleProfile(
    style_id="data_wall",
    family="presentation_heavy",
    headline_mode="metric",
    sentence_density="sparse",
    bullet_tempo="tight",
    tone="data_maximalist",
    evidence_density="heavy",
    preferred_slide_types=["traction", "financial", "market", "competition"],
    presentation_rules={
        "max_words_title": 4,
        "max_bullets": 6,
        "bullet_starts_with": "kpi_with_value",
        "hero_stat_required": True,
        "no_adjectives": True,
        "title_format": "metric_category",
        "subtitle_allowed": False,
        "multiple_charts_per_slide": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": True,
        "data_first": True,
        "data_density_high": True,
        "max_body_sections": 4,
        "paragraph_max_sentences": 3,
    },
    fluff_tolerance=0.0,
    number_format="compact",
    citation_style="inline",
    visual_preference="multi_chart_dashboard",
    max_bullets_presentation=6,
    max_words_per_bullet=8,
))

_register(StyleProfile(
    style_id="neo_corporate",
    family="presentation_heavy",
    headline_mode="statement",
    sentence_density="moderate",
    bullet_tempo="mixed",
    tone="modern_corporate",
    evidence_density="moderate",
    preferred_slide_types=["solution", "market", "gtm", "team"],
    presentation_rules={
        "max_words_title": 8,
        "max_bullets": 5,
        "bullet_starts_with": "professional_claim",
        "hero_stat_required": False,
        "no_adjectives": False,
        "title_format": "corporate_headline",
        "subtitle_allowed": True,
        "icon_per_bullet": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": True,
        "data_first": False,
        "structured_sections": True,
        "max_body_sections": 4,
        "paragraph_max_sentences": 5,
    },
    fluff_tolerance=0.1,
    number_format="abbreviated",
    citation_style="footnote",
    visual_preference="icon_grid",
    max_bullets_presentation=5,
    max_words_per_bullet=14,
))

_register(StyleProfile(
    style_id="luxury_brand",
    family="presentation_heavy",
    headline_mode="statement",
    sentence_density="sparse",
    bullet_tempo="flowing",
    tone="premium_refined",
    evidence_density="light",
    preferred_slide_types=["title", "solution", "product_demo", "team"],
    presentation_rules={
        "max_words_title": 5,
        "max_bullets": 3,
        "bullet_starts_with": "curated_phrase",
        "hero_stat_required": False,
        "no_adjectives": False,
        "title_format": "understated_elegance",
        "subtitle_allowed": True,
        "whitespace_dominant": True,
    },
    reading_rules={
        "include_assumptions": False,
        "include_risks": False,
        "citation_required": False,
        "data_first": False,
        "aspirational_narrative": True,
        "max_body_sections": 2,
        "paragraph_max_sentences": 4,
    },
    fluff_tolerance=0.25,
    number_format="full",
    citation_style="appendix",
    visual_preference="premium_photography",
    max_bullets_presentation=3,
    max_words_per_bullet=10,
))

_register(StyleProfile(
    style_id="brutalist_signal",
    family="presentation_heavy",
    headline_mode="metric",
    sentence_density="sparse",
    bullet_tempo="tight",
    tone="brutalist_raw",
    evidence_density="moderate",
    preferred_slide_types=["traction", "problem", "financial", "ask"],
    presentation_rules={
        "max_words_title": 3,
        "max_bullets": 3,
        "bullet_starts_with": "raw_fact",
        "hero_stat_required": True,
        "no_adjectives": True,
        "title_format": "single_word_or_number",
        "subtitle_allowed": False,
        "monospace_aesthetic": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": True,
        "data_first": True,
        "no_narrative_framing": True,
        "max_body_sections": 2,
        "paragraph_max_sentences": 3,
    },
    fluff_tolerance=0.0,
    number_format="compact",
    citation_style="inline",
    visual_preference="text_only_bold",
    max_bullets_presentation=3,
    max_words_per_bullet=8,
))

_register(StyleProfile(
    style_id="demo_showcase",
    family="presentation_heavy",
    headline_mode="statement",
    sentence_density="sparse",
    bullet_tempo="staccato",
    tone="demo_walkthrough",
    evidence_density="light",
    preferred_slide_types=["product_demo", "solution", "traction", "title"],
    presentation_rules={
        "max_words_title": 6,
        "max_bullets": 4,
        "bullet_starts_with": "feature_or_step",
        "hero_stat_required": False,
        "no_adjectives": False,
        "title_format": "feature_headline",
        "subtitle_allowed": True,
        "screenshot_per_slide": True,
    },
    reading_rules={
        "include_assumptions": False,
        "include_risks": False,
        "citation_required": False,
        "data_first": False,
        "step_by_step_walkthrough": True,
        "max_body_sections": 3,
        "paragraph_max_sentences": 3,
    },
    fluff_tolerance=0.1,
    number_format="compact",
    citation_style="appendix",
    visual_preference="product_screenshot",
    max_bullets_presentation=4,
    max_words_per_bullet=12,
))


# ════════════════════════════════════════════════════════════════════
# FAMILY 7: Sector-Specific (8 styles)
# ════════════════════════════════════════════════════════════════════

_register(StyleProfile(
    style_id="saas_metrics_first",
    family="sector_specific",
    headline_mode="metric",
    sentence_density="sparse",
    bullet_tempo="tight",
    tone="saas_operator",
    evidence_density="heavy",
    preferred_slide_types=["financial", "traction", "gtm", "competition"],
    presentation_rules={
        "max_words_title": 6,
        "max_bullets": 5,
        "bullet_starts_with": "saas_kpi",
        "hero_stat_required": True,
        "no_adjectives": True,
        "title_format": "saas_metric_headline",
        "subtitle_allowed": False,
        "arr_mrr_required": True,
        "magic_number_shown": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": True,
        "data_first": True,
        "saas_benchmarks_referenced": True,
        "net_revenue_retention": True,
        "rule_of_40_check": True,
        "max_body_sections": 4,
        "paragraph_max_sentences": 4,
    },
    fluff_tolerance=0.0,
    number_format="compact",
    citation_style="inline",
    visual_preference="saas_metrics_dashboard",
    max_bullets_presentation=5,
    max_words_per_bullet=11,
))

_register(StyleProfile(
    style_id="ai_infra_technical",
    family="sector_specific",
    headline_mode="statement",
    sentence_density="moderate",
    bullet_tempo="mixed",
    tone="ai_technical_depth",
    evidence_density="heavy",
    preferred_slide_types=["solution", "product_demo", "competition", "market"],
    presentation_rules={
        "max_words_title": 8,
        "max_bullets": 5,
        "bullet_starts_with": "technical_spec_or_benchmark",
        "hero_stat_required": True,
        "no_adjectives": True,
        "title_format": "technical_capability",
        "subtitle_allowed": True,
        "latency_throughput_shown": True,
        "model_performance_benchmarks": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": True,
        "data_first": True,
        "architecture_explained": True,
        "benchmark_comparisons": True,
        "inference_cost_analysis": True,
        "max_body_sections": 5,
        "paragraph_max_sentences": 5,
    },
    fluff_tolerance=0.0,
    number_format="scientific",
    citation_style="inline",
    visual_preference="architecture_and_benchmark",
    max_bullets_presentation=5,
    max_words_per_bullet=13,
))

_register(StyleProfile(
    style_id="biotech_evidence",
    family="sector_specific",
    headline_mode="statement",
    sentence_density="dense",
    bullet_tempo="flowing",
    tone="biotech_scientific",
    evidence_density="heavy",
    preferred_slide_types=["solution", "market", "team", "traction"],
    presentation_rules={
        "max_words_title": 10,
        "max_bullets": 5,
        "bullet_starts_with": "trial_result_or_mechanism",
        "hero_stat_required": False,
        "no_adjectives": True,
        "title_format": "scientific_finding",
        "subtitle_allowed": True,
        "pipeline_stage_shown": True,
        "ip_portfolio_noted": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": True,
        "data_first": True,
        "mechanism_of_action": True,
        "clinical_pipeline": True,
        "patent_landscape": True,
        "max_body_sections": 6,
        "paragraph_max_sentences": 6,
    },
    fluff_tolerance=0.0,
    number_format="scientific",
    citation_style="footnote",
    visual_preference="pipeline_diagram",
    max_bullets_presentation=5,
    max_words_per_bullet=16,
))

_register(StyleProfile(
    style_id="defense_security",
    family="sector_specific",
    headline_mode="statement",
    sentence_density="moderate",
    bullet_tempo="tight",
    tone="defense_classified_tone",
    evidence_density="moderate",
    preferred_slide_types=["solution", "market", "competition", "team"],
    presentation_rules={
        "max_words_title": 8,
        "max_bullets": 5,
        "bullet_starts_with": "capability_or_certification",
        "hero_stat_required": False,
        "no_adjectives": True,
        "title_format": "capability_statement",
        "subtitle_allowed": True,
        "clearance_levels_noted": True,
        "compliance_certifications": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": True,
        "data_first": False,
        "procurement_pathway": True,
        "itar_compliance": True,
        "sbir_sttr_eligibility": True,
        "max_body_sections": 5,
        "paragraph_max_sentences": 5,
    },
    fluff_tolerance=0.0,
    number_format="abbreviated",
    citation_style="footnote",
    visual_preference="capability_matrix",
    max_bullets_presentation=5,
    max_words_per_bullet=13,
))

_register(StyleProfile(
    style_id="retail_ops",
    family="sector_specific",
    headline_mode="metric",
    sentence_density="moderate",
    bullet_tempo="mixed",
    tone="retail_operational",
    evidence_density="moderate",
    preferred_slide_types=["traction", "gtm", "financial", "market"],
    presentation_rules={
        "max_words_title": 7,
        "max_bullets": 5,
        "bullet_starts_with": "store_metric_or_unit_economics",
        "hero_stat_required": True,
        "no_adjectives": True,
        "title_format": "retail_kpi",
        "subtitle_allowed": True,
        "same_store_sales_growth": True,
        "inventory_turns_shown": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": True,
        "data_first": True,
        "unit_economics_per_store": True,
        "supply_chain_overview": True,
        "seasonality_noted": True,
        "max_body_sections": 4,
        "paragraph_max_sentences": 5,
    },
    fluff_tolerance=0.0,
    number_format="compact",
    citation_style="inline",
    visual_preference="retail_metrics_grid",
    max_bullets_presentation=5,
    max_words_per_bullet=12,
))

_register(StyleProfile(
    style_id="education_outcomes",
    family="sector_specific",
    headline_mode="statement",
    sentence_density="moderate",
    bullet_tempo="flowing",
    tone="education_evidence_based",
    evidence_density="heavy",
    preferred_slide_types=["problem", "solution", "traction", "market"],
    presentation_rules={
        "max_words_title": 8,
        "max_bullets": 5,
        "bullet_starts_with": "learning_outcome_or_metric",
        "hero_stat_required": True,
        "no_adjectives": False,
        "title_format": "outcome_headline",
        "subtitle_allowed": True,
        "efficacy_study_referenced": True,
        "student_impact_shown": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": True,
        "data_first": True,
        "pedagogical_framework": True,
        "outcome_measurement": True,
        "equity_considerations": True,
        "max_body_sections": 5,
        "paragraph_max_sentences": 5,
    },
    fluff_tolerance=0.05,
    number_format="abbreviated",
    citation_style="footnote",
    visual_preference="before_after_comparison",
    max_bullets_presentation=5,
    max_words_per_bullet=14,
))

_register(StyleProfile(
    style_id="mobility_logistics",
    family="sector_specific",
    headline_mode="metric",
    sentence_density="moderate",
    bullet_tempo="tight",
    tone="logistics_operational",
    evidence_density="heavy",
    preferred_slide_types=["market", "solution", "traction", "financial"],
    presentation_rules={
        "max_words_title": 7,
        "max_bullets": 5,
        "bullet_starts_with": "operational_metric_or_route",
        "hero_stat_required": True,
        "no_adjectives": True,
        "title_format": "operations_kpi",
        "subtitle_allowed": True,
        "fleet_utilization_shown": True,
        "route_optimization_data": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": True,
        "data_first": True,
        "cost_per_mile_analysis": True,
        "regulatory_environment": True,
        "autonomous_readiness": True,
        "max_body_sections": 4,
        "paragraph_max_sentences": 5,
    },
    fluff_tolerance=0.0,
    number_format="compact",
    citation_style="inline",
    visual_preference="map_overlay",
    max_bullets_presentation=5,
    max_words_per_bullet=12,
))

_register(StyleProfile(
    style_id="real_estate_workflow",
    family="sector_specific",
    headline_mode="metric",
    sentence_density="moderate",
    bullet_tempo="mixed",
    tone="real_estate_transactional",
    evidence_density="moderate",
    preferred_slide_types=["market", "financial", "traction", "solution"],
    presentation_rules={
        "max_words_title": 7,
        "max_bullets": 5,
        "bullet_starts_with": "deal_metric_or_workflow_step",
        "hero_stat_required": True,
        "no_adjectives": True,
        "title_format": "deal_flow_headline",
        "subtitle_allowed": True,
        "cap_rate_shown": True,
        "occupancy_metrics": True,
    },
    reading_rules={
        "include_assumptions": True,
        "include_risks": True,
        "citation_required": True,
        "data_first": True,
        "comparable_properties": True,
        "zoning_regulatory": True,
        "cash_flow_projections": True,
        "max_body_sections": 4,
        "paragraph_max_sentences": 5,
    },
    fluff_tolerance=0.0,
    number_format="full",
    citation_style="footnote",
    visual_preference="property_comparison_table",
    max_bullets_presentation=5,
    max_words_per_bullet=13,
))


# ════════════════════════════════════════════════════════════════════
# LOOKUP FUNCTIONS
# ════════════════════════════════════════════════════════════════════


def get_style(style_id: str) -> StyleProfile:
    """Get a style by ID. Returns yc_crisp as default."""
    return STYLE_CATALOG.get(style_id, STYLE_CATALOG["yc_crisp"])


def get_family(family: str) -> list[StyleProfile]:
    """Get all styles in a family."""
    return [s for s in STYLE_CATALOG.values() if s.family == family]


def get_all_families() -> list[str]:
    """Get list of all family names."""
    return sorted(set(s.family for s in STYLE_CATALOG.values()))


def list_styles() -> list[dict[str, str]]:
    """Return summary list of all styles for API responses."""
    return [
        {"style_id": s.style_id, "family": s.family, "tone": s.tone}
        for s in STYLE_CATALOG.values()
    ]


# ════════════════════════════════════════════════════════════════════
# AUTO-SELECT
# ════════════════════════════════════════════════════════════════════

# Scoring weights for style selection
_AUDIENCE_PREFERENCE: dict[str, list[str]] = {
    "investors": ["fundraise_core", "investor_diligence"],
    "board": ["investor_diligence", "reading_heavy"],
    "customers": ["product_gtm", "presentation_heavy"],
    "internal": ["reading_heavy", "product_gtm"],
    "technical": ["reading_heavy", "sector_specific"],
    "general": ["presentation_heavy", "fundraise_core"],
}

_DECK_TYPE_PREFERENCE: dict[str, list[str]] = {
    "pitch": ["fundraise_core", "founder_story"],
    "fundraise": ["fundraise_core", "investor_diligence"],
    "diligence": ["investor_diligence", "reading_heavy"],
    "product": ["product_gtm", "presentation_heavy"],
    "keynote": ["presentation_heavy", "founder_story"],
    "report": ["reading_heavy", "investor_diligence"],
    "update": ["reading_heavy", "founder_story"],
    "demo": ["presentation_heavy", "product_gtm"],
}

_SECTOR_STYLE_MAP: dict[str, str] = {
    "saas": "saas_metrics_first",
    "ai": "ai_infra_technical",
    "ml": "ai_infra_technical",
    "biotech": "biotech_evidence",
    "pharma": "biotech_evidence",
    "defense": "defense_security",
    "security": "defense_security",
    "retail": "retail_ops",
    "ecommerce": "retail_ops",
    "education": "education_outcomes",
    "edtech": "education_outcomes",
    "mobility": "mobility_logistics",
    "logistics": "mobility_logistics",
    "real_estate": "real_estate_workflow",
    "proptech": "real_estate_workflow",
    "fintech": "fintech_trust",
    "healthtech": "healthtech_clinical",
    "climate": "climate_impact",
    "cleantech": "climate_impact",
    "devtools": "developer_tooling",
    "marketplace": "marketplace_liquidity",
    "consumer": "consumer_viral",
}

_STAGE_PREFERENCE: dict[str, list[str]] = {
    "pre_seed": ["scrappy_builder", "first_round_founder", "yc_crisp"],
    "seed": ["yc_crisp", "first_round_founder", "sequoia_narrative"],
    "series_a": ["sequoia_narrative", "a16z_thesis", "benchmark_product_first"],
    "series_b": ["a16z_thesis", "bessemer_cloud", "accel_growth"],
    "series_c": ["tiger_numbers_first", "accel_growth", "bessemer_cloud"],
    "growth": ["tiger_numbers_first", "accel_growth", "board_memo"],
    "pre_ipo": ["board_memo", "analyst_brief", "ic_memo"],
}


def select_style(
    audience: str = "investors",
    deck_type: str = "pitch",
    sector: str | None = None,
    stage: str | None = None,
) -> StyleProfile:
    """Auto-select the best style based on deck metadata.

    Scoring:
    1. If sector has a dedicated style, weight it heavily.
    2. Audience preference narrows family.
    3. Deck type narrows further.
    4. Stage picks from remaining candidates.
    """
    # Direct sector match gets highest priority
    if sector and sector.lower() in _SECTOR_STYLE_MAP:
        sector_style = _SECTOR_STYLE_MAP[sector.lower()]
        if sector_style in STYLE_CATALOG:
            return STYLE_CATALOG[sector_style]

    # Score each style
    scores: dict[str, float] = {sid: 0.0 for sid in STYLE_CATALOG}

    # Audience scoring (weight=3)
    audience_families = _AUDIENCE_PREFERENCE.get(audience.lower(), [])
    for sid, style in STYLE_CATALOG.items():
        if style.family in audience_families:
            idx = audience_families.index(style.family)
            scores[sid] += (len(audience_families) - idx) * 3.0

    # Deck type scoring (weight=2)
    deck_families = _DECK_TYPE_PREFERENCE.get(deck_type.lower(), [])
    for sid, style in STYLE_CATALOG.items():
        if style.family in deck_families:
            idx = deck_families.index(style.family)
            scores[sid] += (len(deck_families) - idx) * 2.0

    # Stage preference scoring (weight=4 — most specific)
    if stage and stage.lower() in _STAGE_PREFERENCE:
        preferred_ids = _STAGE_PREFERENCE[stage.lower()]
        for sid in preferred_ids:
            if sid in scores:
                idx = preferred_ids.index(sid)
                scores[sid] += (len(preferred_ids) - idx) * 4.0

    # Pick top scorer, fallback to yc_crisp
    best_id = max(scores, key=lambda k: scores[k])
    if scores[best_id] == 0.0:
        return STYLE_CATALOG["yc_crisp"]
    return STYLE_CATALOG[best_id]
