"""Purpose-specific configurations for Standard Mode.

This module provides purpose configurations and tooltip data for the frontend.
Each purpose has detailed configuration including content tone, narrative style,
vocabulary guidelines, and tooltip information for user-friendly selection.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from typing import Optional

import structlog

logger = structlog.get_logger(__name__)


@dataclass(frozen=True)
class PurposeConfig:
    """Configuration for a specific purpose."""
    
    purpose_id: str
    website_label: str
    content_tone: str
    narrative_style: str
    vocabulary_guidelines: list[str]
    sentence_structure: str
    focus_area: str
    word_count_limit: Optional[int]
    technical_depth: str  # low, medium, high
    visual_density: str  # minimal, balanced, dense
    layout_hints: list[str]
    forbidden_words: list[str]
    required_elements: list[str]


PURPOSE_CONFIGS: dict[str, PurposeConfig] = {
    "deep_tech": PurposeConfig(
        purpose_id="deep_tech",
        website_label="Technical Deep-Dive",
        content_tone="Cold, objective, empirical",
        narrative_style="Structural (Environment → Engine → Output)",
        vocabulary_guidelines=["efficient", "low-latency", "idempotent", "deterministic", "O(n)"],
        sentence_structure="Complex/Technical",
        focus_area="How it works",
        word_count_limit=None,
        technical_depth="high",
        visual_density="dense",
        layout_hints=["technical_spec", "diagram", "code_snippet"],
        forbidden_words=["amazing", "revolutionary", "game-changing"],
        required_elements=["architecture", "performance_metrics", "versioning"],
    ),
    "vc_pitch": PurposeConfig(
        purpose_id="vc_pitch",
        website_label="VC Investment Deck",
        content_tone="High-energy, urgent, ambitious",
        narrative_style="Persuasive (Why Now?)",
        vocabulary_guidelines=["dominate", "capture", "disrupt", "scale", "traction"],
        sentence_structure="Short/Punchy",
        focus_area="Why it wins",
        word_count_limit=15,
        technical_depth="medium",
        visual_density="balanced",
        layout_hints=["stat-hero", "chart-focus", "comparison"],
        forbidden_words=["nice-to-have", "maybe", "potentially"],
        required_elements=["traction", "market_size", "unit_economics"],
    ),
    "executive_brief": PurposeConfig(
        purpose_id="executive_brief",
        website_label="Executive Summary",
        content_tone="Professional, concise, bottom-line",
        narrative_style="Result-First (P&L impact)",
        vocabulary_guidelines=["ROI", "KPI", "impact", "strategic", "quantifiable"],
        sentence_structure="Bulleted/Direct",
        focus_area="The ROI",
        word_count_limit=10,
        technical_depth="medium",
        visual_density="minimal",
        layout_hints=["bullet-points", "table", "stat-hero"],
        forbidden_words=["exciting", "innovative", "cutting-edge"],
        required_elements=["executive_summary", "key_metrics", "recommendation"],
    ),
    "trust_compliance": PurposeConfig(
        purpose_id="trust_compliance",
        website_label="Trust & Compliance Deck",
        content_tone="Conservative, authoritative, reassuring",
        narrative_style="Validation (remove buyer's remorse)",
        vocabulary_guidelines=["ISO", "SOC2", "HIPAA", "GDPR", "certified", "audited"],
        sentence_structure="Long/Detailed",
        focus_area="The Safety",
        word_count_limit=None,
        technical_depth="high",
        visual_density="dense",
        layout_hints=["table", "bullet-points", "comparison"],
        forbidden_words=["innovative", "revolutionary", "game-changing"],
        required_elements=["certifications", "security_measures", "compliance"],
    ),
    "cinematic_keynote": PurposeConfig(
        purpose_id="cinematic_keynote",
        website_label="Cinematic Keynote",
        content_tone="Poetic, minimalist, inspiring",
        narrative_style="Cinematic (Human Impact)",
        vocabulary_guidelines=["speed", "thought", "possibility", "future", "impact"],
        sentence_structure="Single Phrases",
        focus_area="The Feeling",
        word_count_limit=5,
        technical_depth="low",
        visual_density="minimal",
        layout_hints=["title-only", "image-full", "quote"],
        forbidden_words=["metrics", "data", "analysis", "implementation"],
        required_elements=["vision", "emotional_hook", "call_to_action"],
    ),
    "seed_round": PurposeConfig(
        purpose_id="seed_round",
        website_label="Seed Round Pitch",
        content_tone="Optimistic, vision-focused",
        narrative_style="Story-driven (founder journey)",
        vocabulary_guidelines=["we", "our", "vision", "founded", "believes"],
        sentence_structure="Narrative",
        focus_area="The Vision",
        word_count_limit=None,
        technical_depth="low",
        visual_density="balanced",
        layout_hints=["two-column", "image-full", "grid-3"],
        forbidden_words=["metrics", "financials", "projections"],
        required_elements=["founder_story", "vision", "early_traction"],
    ),
    "series_a": PurposeConfig(
        purpose_id="series_a",
        website_label="Series A Growth",
        content_tone="Data-driven, metrics-heavy",
        narrative_style="Evidence-First (traction proof)",
        vocabulary_guidelines=["MoM", "YoY", "CAC", "LTV", "churn", "ARR"],
        sentence_structure="Data-heavy",
        focus_area="The Traction",
        word_count_limit=None,
        technical_depth="medium",
        visual_density="dense",
        layout_hints=["chart-focus", "table", "stat-hero"],
        forbidden_words=["vision", "potential", "could"],
        required_elements=["growth_metrics", "unit_economics", "traction"],
    ),
    "partnership": PurposeConfig(
        purpose_id="partnership",
        website_label="Partnership Deck",
        content_tone="Collaborative, mutual benefit",
        narrative_style="Relationship-focused (win-win)",
        vocabulary_guidelines=["synergy", "integration", "partnership", "mutual", "shared"],
        sentence_structure="Balanced",
        focus_area="The Synergy",
        word_count_limit=None,
        technical_depth="medium",
        visual_density="balanced",
        layout_hints=["comparison", "diagram", "grid-3"],
        forbidden_words=["compete", "beat", "defeat"],
        required_elements=["value_proposition", "integration_path", "mutual_benefit"],
    ),
    "customer_case": PurposeConfig(
        purpose_id="customer_case",
        website_label="Customer Case Study",
        content_tone="Evidence-based, testimonial",
        narrative_style="Success story (problem → solution)",
        vocabulary_guidelines=["they", "their", "achieved", "resulted", "success"],
        sentence_structure="Narrative",
        focus_area="The Proof",
        word_count_limit=None,
        technical_depth="low",
        visual_density="balanced",
        layout_hints=["quote", "two-column", "stat-hero"],
        forbidden_words=["we", "our", "our_product"],
        required_elements=["customer_profile", "challenge", "results", "testimonial"],
    ),
    "fundraising_roadshow": PurposeConfig(
        purpose_id="fundraising_roadshow",
        website_label="Fundraising Roadshow",
        content_tone="Confident, prepared, professional",
        narrative_style="Roadshow narrative (market opportunity)",
        vocabulary_guidelines=["TAM", "SAM", "SOM", "CAGR", "market", "opportunity"],
        sentence_structure="Strategic",
        focus_area="The Market",
        word_count_limit=None,
        technical_depth="medium",
        visual_density="dense",
        layout_hints=["stat-hero", "chart-focus", "comparison"],
        forbidden_words=["maybe", "potentially", "could"],
        required_elements=["investment_thesis", "market_size", "traction"],
    ),
    "growth_deck": PurposeConfig(
        purpose_id="growth_deck",
        website_label="Growth Deck",
        content_tone="Metrics-driven, performance-focused",
        narrative_style="KPI-driven (growth trajectory)",
        vocabulary_guidelines=["MoM", "QoQ", "YoY", "growth", "optimization", "funnel"],
        sentence_structure="Data-heavy",
        focus_area="The Growth",
        word_count_limit=None,
        technical_depth="medium",
        visual_density="dense",
        layout_hints=["chart-focus", "table", "grid-3"],
        forbidden_words=["vision", "potential", "could"],
        required_elements=["growth_metrics", "growth_strategy", "experiments"],
    ),
    "market_analysis": PurposeConfig(
        purpose_id="market_analysis",
        website_label="Market Analysis",
        content_tone="Research-heavy, analytical",
        narrative_style="Deep dive (market landscape)",
        vocabulary_guidelines=["TAM", "SAM", "SOM", "CAGR", "segment", "trends"],
        sentence_structure="Analytical",
        focus_area="The Market",
        word_count_limit=None,
        technical_depth="medium",
        visual_density="dense",
        layout_hints=["chart-focus", "comparison", "grid-3"],
        forbidden_words=["we", "our", "our_product"],
        required_elements=["market_size", "trends", "customer_segments", "competition"],
    ),
    "competitive_analysis": PurposeConfig(
        purpose_id="competitive_analysis",
        website_label="Competitive Analysis",
        content_tone="Comparative, positioning-focused",
        narrative_style="Competitive landscape (vs others)",
        vocabulary_guidelines=["differentiator", "moat", "positioning", "advantage", "vs"],
        sentence_structure="Comparative",
        focus_area="The Position",
        word_count_limit=None,
        technical_depth="medium",
        visual_density="dense",
        layout_hints=["comparison", "table", "diagram"],
        forbidden_words=["better", "best", "superior"],
        required_elements=["competitive_landscape", "differentiators", "positioning"],
    ),
    "team_deck": PurposeConfig(
        purpose_id="team_deck",
        website_label="Team Deck",
        content_tone="Talent-focused, credibility",
        narrative_style="Team narrative (who we are)",
        vocabulary_guidelines=["expertise", "experience", "background", "credentials", "track_record"],
        sentence_structure="Narrative",
        focus_area="The Team",
        word_count_limit=None,
        technical_depth="low",
        visual_density="balanced",
        layout_hints=["grid-3", "diagram", "two-column"],
        forbidden_words=["metrics", "data", "financials"],
        required_elements=["founders", "leadership", "expertise", "credibility"],
    ),
    "financial_projection": PurposeConfig(
        purpose_id="financial_projection",
        website_label="Financial Projection",
        content_tone="Financial, projection-focused",
        narrative_style="Financial narrative (numbers story)",
        vocabulary_guidelines=["ARR", "MRR", "burn_rate", "runway", "EBITDA", "gross_margin"],
        sentence_structure="Data-heavy",
        focus_area="The Numbers",
        word_count_limit=None,
        technical_depth="high",
        visual_density="dense",
        layout_hints=["table", "chart-focus", "stat-hero"],
        forbidden_words=["vision", "potential", "could"],
        required_elements=["assumptions", "revenue", "expenses", "cash_flow", "projections"],
    ),
    "product_roadmap": PurposeConfig(
        purpose_id="product_roadmap",
        website_label="Product Roadmap",
        content_tone="Visionary, timeline-focused",
        narrative_style="Roadmap narrative (future plans)",
        vocabulary_guidelines=["milestone", "timeline", "release", "feature", "priority"],
        sentence_structure="Strategic",
        focus_area="The Future",
        word_count_limit=None,
        technical_depth="medium",
        visual_density="balanced",
        layout_hints=["timeline", "process", "grid-3"],
        forbidden_words=["maybe", "potentially", "could"],
        required_elements=["vision", "near_term", "mid_term", "long_term", "priorities"],
    ),
    "milestone_deck": PurposeConfig(
        purpose_id="milestone_deck",
        website_label="Milestone Deck",
        content_tone="Achievement-focused, proud",
        narrative_style="Milestone-driven (what we've done)",
        vocabulary_guidelines=["launched", "shipped", "achieved", "reached", "completed"],
        sentence_structure="Bulleted",
        focus_area="The Achievements",
        word_count_limit=None,
        technical_depth="low",
        visual_density="balanced",
        layout_hints=["timeline", "grid-3", "chart-focus"],
        forbidden_words=["will", "plan", "future"],
        required_elements=["achievements", "metrics", "timeline", "celebration"],
    ),
    "crisis_management": PurposeConfig(
        purpose_id="crisis_management",
        website_label="Crisis Management",
        content_tone="Transparent, accountable",
        narrative_style="Crisis narrative (addressing issues)",
        vocabulary_guidelines=["transparency", "accountability", "remediation", "prevention", "communication"],
        sentence_structure="Direct",
        focus_area="The Response",
        word_count_limit=None,
        technical_depth="medium",
        visual_density="balanced",
        layout_hints=["timeline", "bullet-points", "two-column"],
        forbidden_words=["minor", "insignificant", "no big deal"],
        required_elements=["situation", "impact", "response", "prevention"],
    ),
    "expansion_plan": PurposeConfig(
        purpose_id="expansion_plan",
        website_label="Expansion Plan",
        content_tone="Ambitious, strategic",
        narrative_style="Expansion narrative (growth plans)",
        vocabulary_guidelines=["geographic", "market", "expansion", "scale", "growth"],
        sentence_structure="Strategic",
        focus_area="The Expansion",
        word_count_limit=None,
        technical_depth="medium",
        visual_density="dense",
        layout_hints=["chart-focus", "timeline", "grid-3"],
        forbidden_words=["maybe", "potentially", "could"],
        required_elements=["current_footprint", "expansion_markets", "timeline", "resources"],
    ),
    "advisory_board": PurposeConfig(
        purpose_id="advisory_board",
        website_label="Advisory Board",
        content_tone="Credibility-focused, prestigious",
        narrative_style="Advisor narrative (who advises us)",
        vocabulary_guidelines=["advisor", "expertise", "network", "guidance", "credibility"],
        sentence_structure="Narrative",
        focus_area="The Advisors",
        word_count_limit=None,
        technical_depth="low",
        visual_density="balanced",
        layout_hints=["grid-3", "two-column", "diagram"],
        forbidden_words=["metrics", "data", "financials"],
        required_elements=["advisors", "value_add", "engagement", "structure"],
    ),
    "strategic_partnership": PurposeConfig(
        purpose_id="strategic_partnership",
        website_label="Strategic Partnership",
        content_tone="Partnership-focused, enterprise",
        narrative_style="Enterprise narrative (strategic alliances)",
        vocabulary_guidelines=["enterprise", "strategic", "alliance", "integration", "partnership"],
        sentence_structure="Professional",
        focus_area="The Partnership",
        word_count_limit=None,
        technical_depth="medium",
        visual_density="dense",
        layout_hints=["diagram", "comparison", "table"],
        forbidden_words=["compete", "beat", "defeat"],
        required_elements=["strategic_fit", "partnership_model", "integration", "governance"],
    ),
    "pre_seed_pitch": PurposeConfig(
        purpose_id="pre_seed_pitch",
        website_label="Pre-Seed Pitch",
        content_tone="Early-stage, vision-focused",
        narrative_style="Founder story (why we exist)",
        vocabulary_guidelines=["idea", "vision", "insight", "opportunity", "founded"],
        sentence_structure="Narrative",
        focus_area="The Idea",
        word_count_limit=None,
        technical_depth="low",
        visual_density="balanced",
        layout_hints=["two-column", "image-full", "grid-3"],
        forbidden_words=["metrics", "financials", "traction"],
        required_elements=["founder_story", "insight", "vision", "early_validation"],
    ),
}


# Tooltip data for frontend - provides detailed explanations for each purpose
PURPOSE_TOOLTIPS: dict[str, dict[str, str | list[str]]] = {
    "deep_tech": {
        "title": "Technical Deep-Dive",
        "description": "For developers and architects explaining technical architecture",
        "use_case": "Best for: SaaS platforms, APIs, developer tools, infrastructure",
        "example_companies": "Stripe, Twilio, AWS, Vercel",
        "key_elements": ["Architecture diagrams", "Performance metrics", "Technical specs"],
        "visual_density": "High (diagrams, code snippets)",
    },
    "vc_pitch": {
        "title": "VC Investment Deck",
        "description": "For fundraising from venture capital investors",
        "use_case": "Best for: Series A, B, C fundraising rounds",
        "example_companies": "Airbnb, Uber, DoorDash, Notion",
        "key_elements": ["Market size", "Unit economics", "Growth metrics"],
        "visual_density": "Medium (charts, graphs)",
    },
    "executive_brief": {
        "title": "Executive Summary",
        "description": "For C-level executives and board members",
        "use_case": "Best for: Board meetings, executive updates, strategic reviews",
        "example_companies": "Fortune 500 companies, enterprise SaaS",
        "key_elements": ["ROI", "KPIs", "Strategic impact"],
        "visual_density": "Low (bullets, tables)",
    },
    "trust_compliance": {
        "title": "Trust & Compliance Deck",
        "description": "For security and compliance focused presentations",
        "use_case": "Best for: Security reviews, compliance audits, enterprise sales",
        "example_companies": "Financial institutions, healthcare, government",
        "key_elements": ["Certifications", "Security measures", "Compliance"],
        "visual_density": "High (detailed tables, checklists)",
    },
    "cinematic_keynote": {
        "title": "Cinematic Keynote",
        "description": "For inspiring, emotionally resonant presentations",
        "use_case": "Best for: Keynote speeches, company events, product launches",
        "example_companies": "Apple, Tesla, TED talks",
        "key_elements": ["Vision", "Emotional hook", "Call to action"],
        "visual_density": "Minimal (powerful images)",
    },
    "seed_round": {
        "title": "Seed Round Pitch",
        "description": "For early-stage fundraising from angel investors",
        "use_case": "Best for: Pre-seed, seed rounds, angel investors",
        "example_companies": "Early-stage startups, YC companies",
        "key_elements": ["Founder story", "Vision", "Early traction"],
        "visual_density": "Medium (balanced visuals)",
    },
    "series_a": {
        "title": "Series A Growth",
        "description": "For Series A fundraising with data-driven proof",
        "use_case": "Best for: Series A fundraising, growth stage",
        "example_companies": "Scale-ups, growth-stage startups",
        "key_elements": ["Growth metrics", "Unit economics", "Traction"],
        "visual_density": "High (charts, graphs, tables)",
    },
    "partnership": {
        "title": "Partnership Deck",
        "description": "For business partnership proposals",
        "use_case": "Best for: Strategic partnerships, joint ventures, integrations",
        "example_companies": "Salesforce partnerships, HubSpot integrations",
        "key_elements": ["Value proposition", "Integration path", "Mutual benefit"],
        "visual_density": "Medium (diagrams, comparisons)",
    },
    "customer_case": {
        "title": "Customer Case Study",
        "description": "For showcasing customer success stories",
        "use_case": "Best for: Customer testimonials, case studies, success stories",
        "example_companies": "B2B SaaS customer success stories",
        "key_elements": ["Customer profile", "Challenge", "Results", "Testimonial"],
        "visual_density": "Medium (quotes, metrics)",
    },
    "fundraising_roadshow": {
        "title": "Fundraising Roadshow",
        "description": "For comprehensive fundraising presentations",
        "use_case": "Best for: Multi-city fundraising roadshows, investor meetings",
        "example_companies": "Late-stage startups, unicorns",
        "key_elements": ["Investment thesis", "Market size", "Traction"],
        "visual_density": "High (extensive charts, graphs)",
    },
    "growth_deck": {
        "title": "Growth Deck",
        "description": "For growth strategy and performance presentations",
        "use_case": "Best for: Growth reviews, investor updates, board meetings",
        "example_companies": "High-growth startups, scale-ups",
        "key_elements": ["Growth metrics", "Growth strategy", "Experiments"],
        "visual_density": "High (extensive charts, graphs)",
    },
    "market_analysis": {
        "title": "Market Analysis",
        "description": "For market research and competitive landscape",
        "use_case": "Best for: Market research, competitive intelligence, strategy",
        "example_companies": "Market research firms, consulting",
        "key_elements": ["Market size", "Trends", "Customer segments", "Competition"],
        "visual_density": "High (charts, graphs, comparisons)",
    },
    "competitive_analysis": {
        "title": "Competitive Analysis",
        "description": "For competitive positioning and differentiation",
        "use_case": "Best for: Competitive positioning, sales enablement, strategy",
        "example_companies": "Competitive intelligence, sales teams",
        "key_elements": ["Competitive landscape", "Differentiators", "Positioning"],
        "visual_density": "High (comparison matrices, charts)",
    },
    "team_deck": {
        "title": "Team Deck",
        "description": "For showcasing team expertise and credibility",
        "use_case": "Best for: Team presentations, hiring, investor meetings",
        "example_companies": "All startups, especially early-stage",
        "key_elements": ["Founders", "Leadership", "Expertise", "Credibility"],
        "visual_density": "Medium (team photos, bios)",
    },
    "financial_projection": {
        "title": "Financial Projection",
        "description": "For financial planning and projections",
        "use_case": "Best for: Financial planning, investor updates, board meetings",
        "example_companies": "All businesses with financial projections",
        "key_elements": ["Assumptions", "Revenue", "Expenses", "Cash flow", "Projections"],
        "visual_density": "High (extensive tables, charts)",
    },
    "product_roadmap": {
        "title": "Product Roadmap",
        "description": "For product planning and roadmap presentations",
        "use_case": "Best for: Product planning, roadmap reviews, stakeholder updates",
        "example_companies": "Product teams, engineering organizations",
        "key_elements": ["Vision", "Near term", "Mid term", "Long term", "Priorities"],
        "visual_density": "Medium (timelines, roadmaps)",
    },
    "milestone_deck": {
        "title": "Milestone Deck",
        "description": "For celebrating achievements and milestones",
        "use_case": "Best for: Company updates, all-hands, investor updates",
        "example_companies": "All companies celebrating achievements",
        "key_elements": ["Achievements", "Metrics", "Timeline", "Celebration"],
        "visual_density": "Medium (timelines, achievement highlights)",
    },
    "crisis_management": {
        "title": "Crisis Management",
        "description": "For crisis response and communication",
        "use_case": "Best for: Crisis communication, stakeholder updates, transparency",
        "example_companies": "Companies in crisis management mode",
        "key_elements": ["Situation", "Impact", "Response", "Prevention"],
        "visual_density": "Medium (timelines, action plans)",
    },
    "expansion_plan": {
        "title": "Expansion Plan",
        "description": "For geographic and market expansion strategy",
        "use_case": "Best for: Expansion planning, international growth, market entry",
        "example_companies": "Global companies, expansion-stage startups",
        "key_elements": ["Current footprint", "Expansion markets", "Timeline", "Resources"],
        "visual_density": "High (maps, charts, timelines)",
    },
    "advisory_board": {
        "title": "Advisory Board",
        "description": "For showcasing advisory board and advisors",
        "use_case": "Best for: Investor meetings, credibility building, strategic guidance",
        "example_companies": "Startups with advisory boards",
        "key_elements": ["Advisors", "Value add", "Engagement", "Structure"],
        "visual_density": "Medium (advisor bios, photos)",
    },
    "strategic_partnership": {
        "title": "Strategic Partnership",
        "description": "For enterprise strategic partnerships",
        "use_case": "Best for: Enterprise partnerships, strategic alliances, joint ventures",
        "example_companies": "Enterprise companies, Fortune 500",
        "key_elements": ["Strategic fit", "Partnership model", "Integration", "Governance"],
        "visual_density": "High (diagrams, integration flows, tables)",
    },
    "pre_seed_pitch": {
        "title": "Pre-Seed Pitch",
        "description": "For very early-stage idea validation",
        "use_case": "Best for: Pre-seed fundraising, idea validation, angel investors",
        "example_companies": "Idea-stage startups, founders",
        "key_elements": ["Founder story", "Insight", "Vision", "Early validation"],
        "visual_density": "Medium (balanced visuals)",
    },
}


def get_purpose_config(purpose_id: str) -> Optional[PurposeConfig]:
    """Get purpose configuration by ID."""
    return PURPOSE_CONFIGS.get(purpose_id)


def get_purpose_tooltip(purpose_id: str) -> Optional[dict[str, str | list[str]]]:
    """Get purpose tooltip data by ID."""
    return PURPOSE_TOOLTIPS.get(purpose_id)


def get_all_purposes() -> list[str]:
    """Get list of all available purpose IDs."""
    return list(PURPOSE_CONFIGS.keys())


__all__ = [
    "PurposeConfig",
    "PURPOSE_CONFIGS",
    "PURPOSE_TOOLTIPS",
    "get_purpose_config",
    "get_purpose_tooltip",
    "get_all_purposes",
]
